---
name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Set up Ruff
        uses: astral-sh/ruff-action@v3
      - name: Run Ruff Check
        run: ruff check --fix
      - name: Run Ruff Format
        run: ruff format
      - name: Run tests
        run: uv run coverage run -m pytest
      - name: Check coverage
        run: uv run coverage report -m
